### ISSUE TITLE
[NOT TRYING TO SPAM] Cub3D == Panda3D Android Engine

### ISSUE THREAD

**Issue by LukongGITHUB** [Moguri/awesome-panda3d#11]
https://m.apkpure.com/cub3d-python-3-6-3d-programming-ide/com.u2600inventions.cub3d

- It can play most Panda3D Samples Folder
 = Can't see BAM [Doesn't use them]
 = Needs to ask which script.py to play/multi-pick if multi-scripts in folder
 = Can't play due to CG Shaders

I'll attach a zip of the test I've done w/your BlenderPanda Plugin also need to do a x86 & Arm64 test.

I was trying to email flavio@ya2.it or see if their is a Project Folder I can test, but I can't seem to find them.

My hope is for a BGE2BAM/Project plugin [BGE-Modifiers, Logic Editor, PBR/BGE-GLSL Materials].
I saw somewhere on one of your post about Android Dev and wonder if you don't know about Cub3D...hopefully UPBGE can help too

**Comment by rdb** [comment]
Cub3D was discontinued some time ago and removed from the Play store.

**Comment by LukongGITHUB** [comment]
FINALLY SOMEONE TOLD ME, BUT THAT STUFF STILL WORKS even without the
PAID EDITOR ADDON.

THE PANDA3D SAMPLES WORKED IN A ANDROID EMULATOR

**Comment by LukongGITHUB** [comment]
I wish I had a backup Editor version, but if someone could mod it so
the 30Day trial was infinite. But do you know why it got removed [My
POV is saying that it just so happen to go down after I started
bragging about it...lost of $5]

**Comment by Moguri** [comment]
This project is not a support forum for Cub3D, and, since it is discontinued, I have no interest in adding it to the list.

**Comment by LukongGITHUB** [comment]
I wasn't asking for support for Cub3D...if this plugin allows BGE
Games to be export into Panda3D Folders then Cub3D can run the games
on Android

...What needs be is Panda3D support... ... ...yeah...though Cub3D
isn't supported...it still works
